"""v6.5

Revision ID: 12a55704da91
Revises: 86bd7ee5f5d
Create Date: 2015-08-19 16:32:11.827563

"""

# revision identifiers, used by Alembic.
revision = '12a55704da91'
down_revision = '86bd7ee5f5d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
