"""v2

Revision ID: 1c37282185a9
Revises: 37fa8f3814b4
Create Date: 2015-08-17 16:56:45.877290

"""

# revision identifiers, used by Alembic.
revision = '1c37282185a9'
down_revision = '37fa8f3814b4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=164), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    ### end Alembic commands ###
