"""v7

Revision ID: 2a5c2ec1237c
Revises: 12a55704da91
Create Date: 2015-08-19 17:01:37.604553

"""

# revision identifiers, used by Alembic.
revision = '2a5c2ec1237c'
down_revision = '12a55704da91'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('author', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'author')
    ### end Alembic commands ###
