"""v23

Revision ID: 34333ffb9060
Revises: 7e8d57e44be
Create Date: 2015-08-28 22:45:05.199330

"""

# revision identifiers, used by Alembic.
revision = '34333ffb9060'
down_revision = '7e8d57e44be'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
