"""v8

Revision ID: 461dc3f270ab
Revises: 2a5c2ec1237c
Create Date: 2015-08-19 17:04:51.372746

"""

# revision identifiers, used by Alembic.
revision = '461dc3f270ab'
down_revision = '2a5c2ec1237c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
