"""v666666

Revision ID: 6a04fc87680
Revises: 461dc3f270ab
Create Date: 2015-08-21 12:09:33.537596

"""

# revision identifiers, used by Alembic.
revision = '6a04fc87680'
down_revision = '461dc3f270ab'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('start', sa.String(length=164), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'start')
    ### end Alembic commands ###
