"""v3.0

Revision ID: 7be1d66bf44
Revises: 1c37282185a9
Create Date: 2015-08-17 23:46:45.061473

"""

# revision identifiers, used by Alembic.
revision = '7be1d66bf44'
down_revision = '1c37282185a9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('tag', sa.String(length=164), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'tag')
    ### end Alembic commands ###
