"""v5

Revision ID: 86bd7ee5f5d
Revises: 7be1d66bf44
Create Date: 2015-08-18 15:16:56.762361

"""

# revision identifiers, used by Alembic.
revision = '86bd7ee5f5d'
down_revision = '7be1d66bf44'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('status', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'status')
    ### end Alembic commands ###
